### ISSUE TITLE
Support for ANSI color codes

### ISSUE THREAD

**Issue by akiakinom** [anthonyhuang07/discord-formatter#1]
Support for even more colors, using ANSI color [escape sequences](https://stackoverflow.com/questions/4842424/list-of-ansi-color-escape-sequences).

For example:

```ansi
[0;40m[1;32mHello
```
would result in:
![image](https://user-images.githubusercontent.com/58445363/188964946-8bcdd449-ff0d-4457-96f1-0261f07afb51.png)

**Comment by anthonyhuang07** [comment]
please provide an example for me to use as I tried different methods but they all didn't work

**Comment by anthonyhuang07** [comment]
well.. you did but the characters appear as question symbols

**Comment by anthonyhuang07** [comment]
nevermind ignore what i said entirely

**Comment by akiakinom** [comment]
bump

**Comment by anthonyhuang07** [comment]
> bump 

Not yet

**Comment by anthonyhuang07** [comment]
ill reopen and work on this issue when I get highlighting to work
